In [3]:
data = pd.Series([1, 3, 5, 7, 9])

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv('C:\\Users\\LENOVO\\Desktop\\DI-BOOTCAMP\\students.csv')

In [7]:
df.head()

,id,first_name,last_name,email,date_of_birth,grade,major,enrollment_year,status
0,1,Alice,Smith,alice.smith1@example.edu,2000-01-15,92,Biology,2016,graduated
1,2,Benjamin,Lee,benjamin.lee2@example.edu,1999-03-22,88,Computer Science,2016,graduated
2,3,Chloe,Johnson,chloe.johnson3@example.edu,2001-05-08,95,Mathematics,2016,graduated
3,4,Daniel,Martinez,daniel.martinez4@example.edu,2000-07-19,84,Engineering,2016,graduated
4,5,Emma,Brown,emma.brown5@example.edu,2002-09-02,91,Psychology,2016,graduated

In [8]:
df.tail()

,id,first_name,last_name,email,date_of_birth,grade,major,enrollment_year,status
94,95,Grace,Wilson,grace.wilson95@example.edu,2001-02-14,93,Literature,2024,active
95,96,Henry,Taylor,henry.taylor96@example.edu,1999-04-30,86,Physics,2024,active
96,97,Isla,Anderson,isla.anderson97@example.edu,2002-06-11,90,Chemistry,2024,active
97,98,Jack,Thomas,jack.thomas98@example.edu,2001-08-23,87,History,2024,active
98,99,Kara,White,kara.white99@example.edu,2000-10-05,94,Art,2024,active

In [2]:
import matplotlib.pyplot as plt

In [1]:
import pandas as pd